# Generated by Django 5.2.5 on 2025-09-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add', 'can_add_book'), ('can_change', 'can_change_book'), ('can_delete', 'can_delete_book')]},
        ),
    ]
