# Generated by Django 5.2.5 on 2025-10-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=50)),
                ('Cost_price', models.IntegerField()),
                ('Selling_price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Category_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.category')),
                ('Supplier_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='product.supplier')),
                ('Warehouse_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='product.warehouse')),
            ],
        ),
    ]
