# Generated by Django 5.2.5 on 2025-10-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseManager',
            fields=[
                ('Manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Manager_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Warehouse_Id',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
