# Generated by Django 5.2.5 on 2025-10-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_warehousemanager_remove_product_warehouse_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=50)),
                ('warehouse_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='product.warehousemanager')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Warehouse_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='product.warehouse'),
        ),
    ]
