# Generated by Django 5.2.5 on 2025-10-10 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_warehouse_product_warehouse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Warehouse_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='product.warehouse'),
        ),
    ]
